defmodule Mix.Tasks.Kumi.Install.Docs do
  @moduledoc false

  def short_doc do
    "Installs Kumi into a host application"
  end

  def example do
    "mix kumi.install"
  end

  def long_doc do
    """
    #{short_doc()}

    Creates `lib/<app>/app.ex` — a `use Kumi.App` skeleton declaring the
    app's name/title and an empty `resources do end` block ready for you to
    list your Ash resources.

    ## Example

    ```bash
    #{example()}
    ```
    """
  end
end

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.Kumi.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()}"

    @moduledoc __MODULE__.Docs.long_doc()

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :kumi,
        adds_deps: [],
        installs: [],
        example: __MODULE__.Docs.example(),
        only: nil,
        positional: [],
        composes: [],
        schema: [],
        defaults: [],
        aliases: [],
        required: []
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      app_module = Igniter.Project.Module.module_name(igniter, "App")
      app_name = Igniter.Project.Application.app_name(igniter)
      title = title_from_app_name(app_name)

      {exists?, igniter} = Igniter.Project.Module.module_exists(igniter, app_module)

      if exists? do
        Igniter.add_notice(
          igniter,
          "Kumi: #{inspect(app_module)} already exists — leaving it untouched."
        )
      else
        contents = """
        @moduledoc \"\"\"
        Kumi app declaration — generated by `mix kumi.install`. See
        `Kumi.App` for the full DSL (admin navigation, workflows, dashboards).
        \"\"\"

        use Kumi.App

        app do
          name #{inspect(app_name)}
          title #{inspect(title)}
        end

        resources do
          # List the Ash resources that make up this app, e.g.:
          #   resource #{inspect(Igniter.Project.Module.module_name(igniter, "MyResource"))}
        end
        """

        igniter
        |> Igniter.Project.Module.create_module(app_module, contents)
        |> Igniter.add_notice("""
        Kumi: created #{inspect(app_module)}.

        Next steps:
          1. Add your Ash resources under `resources do ... end` in that file.
          2. Run `mix kumi.plan` to see the schema diff for those resources.
          3. To mount the admin UI, add kumi_admin as a dependency and run
             `mix kumi_admin.install`.
        """)
      end
    end

    defp title_from_app_name(app_name) do
      app_name
      |> to_string()
      |> String.split("_")
      |> Enum.map_join(" ", &String.capitalize/1)
    end
  end
else
  defmodule Mix.Tasks.Kumi.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()} | Install `igniter` to use"

    @moduledoc __MODULE__.Docs.long_doc()

    use Mix.Task

    def run(_argv) do
      Mix.shell().error("""
      The task 'kumi.install' requires igniter. Please install igniter and try again.

      For more information, see: https://hexdocs.pm/igniter/readme.html#installation
      """)

      exit({:shutdown, 1})
    end
  end
end
