defmodule Kumi.Test.Repo.Migrations.AddAmountCustomIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:kumi_test_deals, [:amount])
  end

  def down do
    drop_if_exists index(:kumi_test_deals, [:amount])
  end
end
