defmodule Kumi.Test.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kumi_test_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:industry, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:kumi_test_accounts, [:name], name: "kumi_test_accounts_unique_name_index")
    )

    create table(:kumi_test_deals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:amount, :decimal)
      add(:stage, :text, default: "lead")
      add(:closed_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :account_id,
        references(:kumi_test_accounts,
          column: :id,
          name: "kumi_test_deals_account_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:kumi_test_deals, "kumi_test_deals_account_id_fkey"))

    drop(table(:kumi_test_deals))

    drop_if_exists(
      unique_index(:kumi_test_accounts, [:name], name: "kumi_test_accounts_unique_name_index")
    )

    drop(table(:kumi_test_accounts))
  end
end
