defmodule Kumi.Test.Repo.Migrations.AddFoundedOnToAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:kumi_test_accounts) do
      add :founded_on, :date
    end
  end

  def down do
    alter table(:kumi_test_accounts) do
      remove :founded_on
    end
  end
end
