defmodule Kumi.Test.Repo.Migrations.AddResourceShorthandTest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kumi_test_resource_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:kumi_test_resource_customers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:email, :text)
      add(:status, :text, default: "lead")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :account_id,
        references(:kumi_test_resource_accounts,
          column: :id,
          name: "kumi_test_resource_customers_account_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:kumi_test_resource_customers_hw, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:email, :text)
      add(:status, :text, default: "lead")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :account_id,
        references(:kumi_test_resource_accounts,
          column: :id,
          name: "kumi_test_resource_customers_hw_account_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:kumi_test_resource_deals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :customer_id,
        references(:kumi_test_resource_customers,
          column: :id,
          name: "kumi_test_resource_deals_customer_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:kumi_test_resource_deals, "kumi_test_resource_deals_customer_id_fkey"))

    drop(table(:kumi_test_resource_deals))

    drop(
      constraint(
        :kumi_test_resource_customers_hw,
        "kumi_test_resource_customers_hw_account_id_fkey"
      )
    )

    drop(table(:kumi_test_resource_customers_hw))

    drop(
      constraint(:kumi_test_resource_customers, "kumi_test_resource_customers_account_id_fkey")
    )

    drop(table(:kumi_test_resource_customers))

    drop(table(:kumi_test_resource_accounts))
  end
end
