defmodule Kumi.Test.Repo.Migrations.AddTypeCoverage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kumi_test_type_coverage, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ratio, :float
      add :payload, :binary
      add :blob, :binary
      add :starts_at, :time_usec
      add :settings, :map, default: %{}
      add :note, :text, default: "it's"
    end
  end

  def down do
    drop table(:kumi_test_type_coverage)
  end
end
