defmodule KumiAdmin.ResourceIndexLive do
  @moduledoc """
  Generic resource list: columns from `Ash.Resource.Info.public_attributes/1`
  (via `KumiAdmin.Columns`), rows via a plain `Ash.read` with query-level
  `limit`/`offset` and a next/prev control.

  Pagination note: this uses `Ash.Query.limit/offset` rather than Ash's
  `page: [limit:, offset:]` action-level pagination feature, because that
  feature requires each resource's `:read` action to declare `pagination
  ...` — true for none of the CRM resources here (including the one
  generated by `Kumi.Resource`, which slice 1 must not touch). Fetching
  `limit + 1` rows and slicing off the extra one gives an honest
  "is there a next page" without needing that declaration anywhere.

  Without an actor, or without access, this renders that state honestly
  instead of crashing — see `KumiAdmin.Router` moduledoc.
  """

  use Phoenix.LiveView

  alias KumiAdmin.Components.Shell

  @page_size 25

  def mount(params, session, socket) do
    context = KumiAdmin.Context.resolve(session, params, socket)

    socket =
      socket
      |> assign(app: context.app, mount_path: context.mount_path)
      |> assign(actor: context.actor, resource: context.resource, offset: 0, search: "")
      |> assign(
        can_create?:
          !!context.resource && KumiAdmin.Capability.can_create?(context.resource, context.actor)
      )
      |> load_page()

    {:ok, socket}
  end

  def handle_event("next", _params, socket) do
    {:noreply, socket |> update(:offset, &(&1 + @page_size)) |> load_page()}
  end

  def handle_event("prev", _params, socket) do
    {:noreply, socket |> update(:offset, &max(&1 - @page_size, 0)) |> load_page()}
  end

  def handle_event("search", %{"q" => term}, socket) do
    {:noreply, socket |> assign(search: term, offset: 0) |> load_page()}
  end

  defp load_page(socket) do
    case socket.assigns.resource do
      nil ->
        assign(socket, error: :not_found, columns: [], records: [], has_more?: false)

      resource ->
        columns = KumiAdmin.Columns.for_resource(resource)
        search_fields = KumiAdmin.Search.searchable_fields(resource)

        query =
          resource
          |> Ash.Query.sort(:id)
          |> KumiAdmin.Search.apply(search_fields, socket.assigns.search)
          |> Ash.Query.limit(@page_size + 1)
          |> Ash.Query.offset(socket.assigns.offset)

        case Ash.read(query, actor: socket.assigns.actor) do
          {:ok, results} ->
            assign(socket,
              error: nil,
              columns: columns,
              records: Enum.take(results, @page_size),
              has_more?: length(results) > @page_size
            )

          {:error, _reason} ->
            assign(socket, error: :forbidden, columns: columns, records: [], has_more?: false)
        end
    end
  end

  def render(assigns) do
    ~H"""
    <Shell.shell app={@app} mount_path={@mount_path} active_resource={@resource}>
      <div class="kumi-admin-actions">
        <h1 class="kumi-admin-title">
          {@resource && KumiAdmin.Label.plural(@resource)}
        </h1>
        <a
          :if={@can_create?}
          href={"#{@mount_path}/#{KumiAdmin.Slug.for_resource(@resource)}/new"}
          class="kumi-admin-button"
        >
          New
        </a>
      </div>

      <form
        :if={is_nil(@error) or @error == :forbidden}
        id="search-form"
        phx-change="search"
        phx-submit="search"
        class="kumi-admin-search"
      >
        <input
          type="search"
          name="q"
          value={@search}
          placeholder="Search…"
          class="kumi-admin-input"
        />
      </form>

      <p :if={@error == :not_found} class="kumi-admin-empty">
        Unknown resource.
      </p>

      <p :if={@error == :forbidden} class="kumi-admin-empty">
        No access or no records.
      </p>

      <p :if={is_nil(@error) and @records == []} class="kumi-admin-empty">
        No records yet.
      </p>

      <table :if={is_nil(@error) and @records != []} class="kumi-admin-table">
        <thead>
          <tr>
            <th :for={column <- @columns}>{Phoenix.Naming.humanize(column)}</th>
          </tr>
        </thead>
        <tbody>
          <tr :for={record <- @records}>
            <td :for={column <- @columns}>
              <a
                :if={column == :id}
                href={"#{@mount_path}/#{KumiAdmin.Slug.for_resource(@resource)}/#{record.id}"}
              >
                {KumiAdmin.Format.cell(column, Map.get(record, column))}
              </a>
              <span :if={column != :id}>
                {KumiAdmin.Format.cell(column, Map.get(record, column))}
              </span>
            </td>
          </tr>
        </tbody>
      </table>

      <div :if={is_nil(@error) and @records != []} class="kumi-admin-pagination">
        <button phx-click="prev" disabled={@offset == 0}>Prev</button>
        <button phx-click="next" disabled={!@has_more?}>Next</button>
      </div>
    </Shell.shell>
    """
  end
end
