defmodule Mix.Tasks.KumiStorage.Install.Docs do
  @moduledoc false

  def short_doc do
    "Installs Kumi Storage into a host application"
  end

  def example do
    "mix kumi_storage.install"
  end

  def long_doc do
    """
    #{short_doc()}

    Runs `kumi.install` first (composed), then:

      1. Generates `lib/<app>/core/attachment.ex` — a PLAIN Ash resource
         (not a `Kumi.Resource` shorthand — blueprint §6 point 1, D1
         "Show Ash") storing uploaded-file metadata, registered in
         `<App>.Core`. `field :name, :image, to: <App>.Core.Attachment`
         in a `Kumi.Resource` `fields do ... end` block targets it.
      2. Adds `config :kumi_storage, backend: KumiStorage.Backend.Local,
         root: "priv/uploads"` if not already configured, and
         `/priv/uploads/` to `.gitignore`.
      3. Forwards a path to `KumiStorage.Plug` in your Phoenix router, if
         one is found (otherwise prints the snippet to add by hand), with
         `config: {<App>.Core.Attachment, :__kumi_storage_config__}` — the
         generated function the plug reads its backend config from.

    ## Example

    ```bash
    #{example()}
    ```
    """
  end
end

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.KumiStorage.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()}"

    @moduledoc __MODULE__.Docs.long_doc()

    use Igniter.Mix.Task

    # One literal for the router forward, the generated URL function and the
    # notices, so they can't disagree.
    @mount_path "/uploads"

    @access_note """
    Files there are public to anyone holding the URL: the random key is the
    only access control, and Ash policies on the Attachment or its parent
    don't apply to the bytes.
    """

    # Uploaded files are user data: never commit them, and never let a
    # `COPY priv priv` or `mix release` pick up the dev ones by accident.
    @gitignore_entry "/priv/uploads/"

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :kumi_storage,
        adds_deps: [],
        installs: [],
        example: __MODULE__.Docs.example(),
        only: nil,
        positional: [],
        composes: ["kumi.install"],
        schema: [],
        defaults: [],
        aliases: [],
        required: []
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      igniter
      |> Igniter.compose_task("kumi.install", [])
      |> generate_attachment()
      |> configure_backend()
      |> mount_plug()
    end

    defp generate_attachment(igniter) do
      attachment_module = Igniter.Project.Module.module_name(igniter, "Core.Attachment")
      {exists?, igniter} = Igniter.Project.Module.module_exists(igniter, attachment_module)

      if exists? do
        Igniter.add_notice(
          igniter,
          "Kumi Storage: #{inspect(attachment_module)} already exists — leaving it untouched."
        )
      else
        domain_module = Igniter.Project.Module.module_name(igniter, "Core")
        repo_module = Igniter.Project.Module.module_name(igniter, "Repo")

        igniter
        |> Igniter.Project.Module.create_module(
          attachment_module,
          attachment_source(attachment_module, domain_module, repo_module)
        )
        |> Ash.Domain.Igniter.add_resource_reference(domain_module, attachment_module)
        |> Igniter.add_notice("""
        Kumi Storage: created #{inspect(attachment_module)} and registered it in
        #{inspect(domain_module)}.
        """)
      end
    end

    defp attachment_source(attachment_module, domain_module, repo_module) do
      """
      @moduledoc \"\"\"
      Uploaded-file metadata — generated by `mix kumi_storage.install`.
      Plain Ash source, fully yours to edit: this is NOT a
      `Kumi.Resource` shorthand (D1 "Show Ash"). Reference it from a
      `Kumi.Resource` with `field :name, :image, to: #{inspect(attachment_module)}`.
      \"\"\"

      use Ash.Resource,
        domain: #{inspect(domain_module)},
        data_layer: AshPostgres.DataLayer

      postgres do
        table "attachments"
        repo #{inspect(repo_module)}
      end

      actions do
        defaults [:read]

        # Storage calls live HERE, not in kumi_admin: this resource is the
        # trust boundary. `source` is a tagged tuple — `{:path, tmp_path}`
        # (what a Plug.Upload/LiveView upload entry hands you) or
        # `{:binary, data}`. `KumiStorage.Upload.prepare/3` measures and
        # validates it, and stores it only once the action runs (after
        # authorization); a create that fails after that deletes the file.
        create :upload do
          accept []

          argument :source, :term, allow_nil?: false
          argument :filename, :string, allow_nil?: false
          argument :content_type, :string, allow_nil?: false
          # Ignored: the size is measured from `source`. Accepted so callers
          # that still send it (kumi_admin does) keep working.
          argument :byte_size, :integer

          change fn changeset, _context ->
            {backend, backend_opts} = __MODULE__.__kumi_storage_config__()

            KumiStorage.Upload.prepare(changeset, backend, backend_opts)
          end
        end

        destroy :destroy do
          primary? true
          require_atomic? false

          # After the commit, so a rolled-back destroy keeps its file. A
          # failed delete is logged; the destroy still succeeds.
          change after_transaction(fn _changeset, result, _context ->
            {backend, backend_opts} = __MODULE__.__kumi_storage_config__()

            KumiStorage.Upload.delete_stored(result, backend, backend_opts)
          end)
        end
      end

      attributes do
        uuid_primary_key :id

        attribute :filename, :string do
          allow_nil? false
          public? true
        end

        attribute :content_type, :string do
          allow_nil? false
          public? true
        end

        attribute :byte_size, :integer do
          allow_nil? false
          public? true
        end

        # Private: the key is the only thing protecting the file's URL, so it
        # stays out of public interfaces (filters, API extensions). Your own
        # reads still load it.
        attribute :storage_key, :string do
          allow_nil? false
          public? false
        end

        timestamps()
      end

      @doc false
      def __kumi_attachment__, do: true

      @doc "Public URL for a stored attachment — matches the `#{@mount_path}` forward this installer adds to your router."
      def __kumi_attachment_url__(record), do: "#{@mount_path}/\#{record.storage_key}"

      @doc \"\"\"
      `{backend, backend_opts}` from `config :kumi_storage` — the one place
      storage config is read. The actions above call it, and so does
      `KumiStorage.Plug` through the `config:` option of its router forward.
      \"\"\"
      def __kumi_storage_config__ do
        {Application.fetch_env!(:kumi_storage, :backend),
         Application.get_all_env(:kumi_storage) |> Keyword.delete(:backend)}
      end
      """
    end

    defp configure_backend(igniter) do
      igniter
      |> Igniter.Project.Config.configure_new(
        "config.exs",
        :kumi_storage,
        [:backend],
        KumiStorage.Backend.Local
      )
      |> Igniter.Project.Config.configure_new(
        "config.exs",
        :kumi_storage,
        [:root],
        "priv/uploads"
      )
      |> ignore_uploads()
      |> Igniter.add_notice("""
      Kumi Storage: #{@gitignore_entry} (the default upload root) is in .gitignore.
      A relative root resolves against the working directory, so in
      production set an absolute one in config/runtime.exs, e.g.

          config :kumi_storage, root: "/var/lib/my_app/uploads"
      """)
    end

    defp ignore_uploads(igniter) do
      Igniter.create_or_update_file(igniter, ".gitignore", @gitignore_entry <> "\n", fn source ->
        Rewrite.Source.update(source, :content, fn content ->
          ignored? =
            content
            |> String.split("\n")
            |> Enum.any?(&(String.trim(&1) in [@gitignore_entry, "/priv/uploads"]))

          if ignored? do
            content
          else
            String.trim_trailing(content) <>
              "\n\n# Uploaded files (kumi_storage's Local backend root).\n" <>
              @gitignore_entry <> "\n"
          end
        end)
      end)
    end

    defp mount_plug(igniter) do
      attachment_module = Igniter.Project.Module.module_name(igniter, "Core.Attachment")

      {igniter, router} =
        Igniter.Libs.Phoenix.select_router(
          igniter,
          "Which router should Kumi Storage serve uploads from?"
        )

      cond do
        router == nil ->
          Igniter.add_notice(igniter, no_router_snippet(attachment_module))

        already_mounted?(igniter, router) ->
          Igniter.add_notice(
            igniter,
            "Kumi Storage: already mounted in #{inspect(router)} — leaving it untouched."
          )

        true ->
          igniter
          |> Igniter.Libs.Phoenix.add_scope("/", forward(attachment_module),
            router: router,
            placement: :after
          )
          |> Igniter.add_notice("""
          Kumi Storage: mounted file serving at #{@mount_path}/:key in #{inspect(router)}.
          #{@access_note}\
          """)
      end
    end

    defp already_mounted?(igniter, router) do
      {_igniter, _source, zipper} = Igniter.Project.Module.find_module!(igniter, router)

      match?(
        {:ok, _},
        Igniter.Code.Common.move_to(zipper, fn z ->
          Igniter.Code.Function.function_call?(z, :forward, [2, 3]) and
            Igniter.Code.Function.argument_equals?(z, 1, KumiStorage.Plug)
        end)
      )
    end

    # The plug resolves its config through the Attachment's
    # __kumi_storage_config__/0 on every request; kumi_storage itself never
    # reads Application config.
    defp forward(attachment_module) do
      "forward #{inspect(@mount_path)}, KumiStorage.Plug, config: {#{inspect(attachment_module)}, :__kumi_storage_config__}"
    end

    defp no_router_snippet(attachment_module) do
      """
      Kumi Storage: no Phoenix router found or selected. Mount it manually:

          #{forward(attachment_module)}

      #{@access_note}\
      """
    end
  end
else
  defmodule Mix.Tasks.KumiStorage.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()} | Install `igniter` to use"

    @moduledoc __MODULE__.Docs.long_doc()

    use Mix.Task

    def run(_argv) do
      Mix.shell().error("""
      The task 'kumi_storage.install' requires igniter. Please install igniter and try again.

      For more information, see: https://hexdocs.pm/igniter/readme.html#installation
      """)

      exit({:shutdown, 1})
    end
  end
end
