defmodule Mix.Tasks.KumiStorage.Install.Docs do
  @moduledoc false

  def short_doc do
    "Installs Kumi Storage into a host application"
  end

  def example do
    "mix kumi_storage.install"
  end

  def long_doc do
    """
    #{short_doc()}

    Runs `kumi.install` first (composed), then:

      1. Generates `lib/<app>/core/attachment.ex` — a PLAIN Ash resource
         (not a `Kumi.Resource` shorthand — blueprint §6 point 1, D1
         "Show Ash") storing uploaded-file metadata, registered in
         `<App>.Core`. `field :name, :image, to: <App>.Core.Attachment`
         in a `Kumi.Resource` `fields do ... end` block targets it.
      2. Adds `config :kumi_storage, backend: KumiStorage.Backend.Local,
         root: "priv/uploads"` if not already configured.
      3. Forwards a path to `KumiStorage.Plug` in your Phoenix router, if
         one is found (otherwise prints the snippet to add by hand).

    ## Example

    ```bash
    #{example()}
    ```
    """
  end
end

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.KumiStorage.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()}"

    @moduledoc __MODULE__.Docs.long_doc()

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :kumi_storage,
        adds_deps: [],
        installs: [],
        example: __MODULE__.Docs.example(),
        only: nil,
        positional: [],
        composes: ["kumi.install"],
        schema: [],
        defaults: [],
        aliases: [],
        required: []
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      igniter
      |> Igniter.compose_task("kumi.install", [])
      |> generate_attachment()
      |> configure_backend()
      |> mount_plug()
    end

    defp generate_attachment(igniter) do
      attachment_module = Igniter.Project.Module.module_name(igniter, "Core.Attachment")
      {exists?, igniter} = Igniter.Project.Module.module_exists(igniter, attachment_module)

      if exists? do
        Igniter.add_notice(
          igniter,
          "Kumi Storage: #{inspect(attachment_module)} already exists — leaving it untouched."
        )
      else
        domain_module = Igniter.Project.Module.module_name(igniter, "Core")
        repo_module = Igniter.Project.Module.module_name(igniter, "Repo")

        igniter
        |> Igniter.Project.Module.create_module(
          attachment_module,
          attachment_source(attachment_module, domain_module, repo_module)
        )
        |> Ash.Domain.Igniter.add_resource_reference(domain_module, attachment_module)
        |> Igniter.add_notice("""
        Kumi Storage: created #{inspect(attachment_module)} and registered it in
        #{inspect(domain_module)}.
        """)
      end
    end

    defp attachment_source(attachment_module, domain_module, repo_module) do
      """
      @moduledoc \"\"\"
      Uploaded-file metadata — generated by `mix kumi_storage.install`
      (blueprint §6). Plain Ash source, fully yours to edit: this is NOT a
      `Kumi.Resource` shorthand (D1 "Show Ash"). Reference it from a
      `Kumi.Resource` with `field :name, :image, to: #{inspect(attachment_module)}`.
      \"\"\"

      use Ash.Resource,
        domain: #{inspect(domain_module)},
        data_layer: AshPostgres.DataLayer

      postgres do
        table "attachments"
        repo #{inspect(repo_module)}
      end

      actions do
        defaults [:read]

        # Storage calls live HERE, not in kumi_admin (blueprint §6 point 8):
        # this resource is the trust boundary. `source` is a tagged tuple —
        # `{:path, tmp_path}` (what a Plug.Upload/LiveView upload entry
        # hands you) or `{:binary, data}`.
        create :upload do
          accept []

          argument :source, :term, allow_nil?: false
          argument :filename, :string, allow_nil?: false
          argument :content_type, :string, allow_nil?: false
          argument :byte_size, :integer, allow_nil?: false

          change fn changeset, _context ->
            source = Ash.Changeset.get_argument(changeset, :source)
            filename = Ash.Changeset.get_argument(changeset, :filename)
            content_type = Ash.Changeset.get_argument(changeset, :content_type)
            byte_size = Ash.Changeset.get_argument(changeset, :byte_size)

            backend = Application.fetch_env!(:kumi_storage, :backend)
            backend_opts = Application.get_all_env(:kumi_storage) |> Keyword.delete(:backend)

            with :ok <-
                   KumiStorage.Validation.validate(filename, content_type, byte_size, backend_opts),
                 {:ok, storage_key} <- backend.store(source, filename, content_type, backend_opts) do
              changeset
              |> Ash.Changeset.force_change_attribute(:filename, filename)
              |> Ash.Changeset.force_change_attribute(:content_type, content_type)
              |> Ash.Changeset.force_change_attribute(:byte_size, byte_size)
              |> Ash.Changeset.force_change_attribute(:storage_key, storage_key)
            else
              {:error, :too_large} ->
                Ash.Changeset.add_error(changeset, field: :byte_size, message: "is too large")

              {:error, :disallowed_content_type} ->
                Ash.Changeset.add_error(changeset,
                  field: :content_type,
                  message: "is not an allowed content type"
                )

              {:error, reason} ->
                Ash.Changeset.add_error(changeset, message: "upload failed: \#{inspect(reason)}")
            end
          end
        end

        destroy :destroy do
          primary? true
          require_atomic? false

          change after_action(fn _changeset, record, _context ->
            backend = Application.fetch_env!(:kumi_storage, :backend)
            backend_opts = Application.get_all_env(:kumi_storage) |> Keyword.delete(:backend)

            case backend.delete(record.storage_key, backend_opts) do
              :ok -> {:ok, record}
              {:error, _reason} -> {:ok, record}
            end
          end)
        end
      end

      attributes do
        uuid_primary_key :id

        attribute :filename, :string do
          allow_nil? false
          public? true
        end

        attribute :content_type, :string do
          allow_nil? false
          public? true
        end

        attribute :byte_size, :integer do
          allow_nil? false
          public? true
        end

        attribute :storage_key, :string do
          allow_nil? false
          public? true
        end

        timestamps()
      end

      @doc false
      def __kumi_attachment__, do: true

      @doc "Public URL for a stored attachment — matches the `/uploads` forward this installer adds to your router."
      def __kumi_attachment_url__(record), do: "/uploads/\#{record.storage_key}"
      """
    end

    defp configure_backend(igniter) do
      igniter
      |> Igniter.Project.Config.configure_new(
        "config.exs",
        :kumi_storage,
        [:backend],
        KumiStorage.Backend.Local
      )
      |> Igniter.Project.Config.configure_new(
        "config.exs",
        :kumi_storage,
        [:root],
        "priv/uploads"
      )
    end

    defp mount_plug(igniter) do
      {igniter, router} =
        Igniter.Libs.Phoenix.select_router(
          igniter,
          "Which router should Kumi Storage serve uploads from?"
        )

      cond do
        router == nil ->
          Igniter.add_notice(igniter, no_router_snippet())

        already_mounted?(igniter, router) ->
          Igniter.add_notice(
            igniter,
            "Kumi Storage: already mounted in #{inspect(router)} — leaving it untouched."
          )

        true ->
          igniter
          |> Igniter.Libs.Phoenix.add_scope("/", "forward \"/uploads\", KumiStorage.Plug",
            router: router,
            placement: :after
          )
          |> Igniter.add_notice(
            "Kumi Storage: mounted file serving at /uploads/:key in #{inspect(router)}."
          )
      end
    end

    defp already_mounted?(igniter, router) do
      {_igniter, _source, zipper} = Igniter.Project.Module.find_module!(igniter, router)

      match?(
        {:ok, _},
        Igniter.Code.Common.move_to(zipper, fn z ->
          Igniter.Code.Function.function_call?(z, :forward, [2]) and
            Igniter.Code.Function.argument_equals?(z, 1, KumiStorage.Plug)
        end)
      )
    end

    defp no_router_snippet do
      """
      Kumi Storage: no Phoenix router found or selected. Mount it manually:

          forward "/uploads", KumiStorage.Plug
      """
    end
  end
else
  defmodule Mix.Tasks.KumiStorage.Install do
    @shortdoc "#{__MODULE__.Docs.short_doc()} | Install `igniter` to use"

    @moduledoc __MODULE__.Docs.long_doc()

    use Mix.Task

    def run(_argv) do
      Mix.shell().error("""
      The task 'kumi_storage.install' requires igniter. Please install igniter and try again.

      For more information, see: https://hexdocs.pm/igniter/readme.html#installation
      """)

      exit({:shutdown, 1})
    end
  end
end
