defmodule Kumi.Resource do
  @moduledoc """
  Shorthand resource DSL (blueprint §3.2, §0 D1 "Show Ash"). This is
  **sugar only**: `use Kumi.Resource` + `fields do ... end` compiles to
  exactly the standard, hand-writable `Ash.Resource` you'd get by typing
  it yourself — `uuid_primary_key`, public attributes, `timestamps()`,
  `actions do defaults [:read, :destroy, create: :*, update: :*] end`, a
  `postgres` block, and `relationships`. There is no wrapper runtime and
  no hidden layer: `mix kumi.expand MyApp.Customer` prints the exact
  source this macro compiles, because both read from the same pure
  function (`Kumi.Resource.Codegen.generate/3`).

      defmodule MyApp.Customer do
        use Kumi.Resource,
          domain: MyApp.Crm,
          repo: MyApp.Repo,
          table: "customers"

        fields do
          field :name, :string, required: true
          field :email, :email
          field :status, :select, options: [:lead, :active, :lost], default: :lead
          belongs_to :account, MyApp.Account
          has_many :deals, MyApp.Deal

          identity :unique_email, [:email]
        end
      end

  Field types: `:string`, `:text` (sugar for `:string` — Ash has no
  distinct long-text type), `:integer`, `:decimal`, `:boolean`, `:date`,
  `:datetime` (→ `:utc_datetime_usec`), `:email` (`:string` + a `match:`
  constraint), `:select` (`:atom` + `one_of:` constraint, `options:`
  required), `:image` (sugar for `belongs_to` — requires `to:` naming an
  Ash resource, e.g. an Attachment resource generated by
  `mix kumi_storage.install`). `required: true` → `allow_nil? false`
  (also honored on `:image`, which emits it onto the generated
  `belongs_to`); `default:` passes through; `:select` additionally
  accepts `options:`. Any other option key raises `ArgumentError` at
  compile time — there's no silent fallback, so a typo like `requried:`
  is caught instead of quietly compiling as `allow_nil? true`.

  `belongs_to name, Dest` takes two options: `required: true`
  (`allow_nil? false` on the generated foreign key) and `on_delete:`
  (`:delete` / `:nilify` / `:nothing` / `:restrict`), which expands to an
  AshPostgres `references do reference ... end` entry. Without
  `on_delete:` the foreign key carries no `ON DELETE` rule at all, so a
  parent row cannot be deleted once anything references it — the value is
  validated at compile time, and only the relationships that ask for one
  appear in the generated `references` block.

  `identity name, [attribute_names]` declares a unique constraint,
  spelled exactly as Ash spells it, and expands to an `identities do
  ... end` block (which AshPostgres turns into a unique index named
  `"<table>_<name>_index"`). It takes no options: `nils_distinct?`,
  `where`, `eager_check?` and `pre_check?` are escape-hatch territory.

  **Escape hatch**: need calculations, aggregates, policies, custom
  actions, or anything else beyond the default four actions? Write the
  Ash resource directly — start from `mix kumi.expand MyApp.Customer`'s
  output and edit it. The shorthand and hand-written Ash never conflict;
  they're the same target.

  Mixing the two in one module instead is rejected at compile time,
  because `mix kumi.expand` would not print the hand-written part.
  `use Kumi.Resource` takes exactly `domain:`, `repo:` and `table:`
  (anything else raises `ArgumentError`), and a `CompileError` is raised
  when the module also contains:

    * `attributes`, `relationships`, `actions`, `identities` or `postgres
      do references do ... end end` entries beyond the ones `fields do ...
      end` generated;
    * any `calculations`, `aggregates`, `code_interface`, `validations`,
      `changes` or `preparations` entry, or any `postgres` `custom_indexes`,
      `check_constraints` or `custom_statements` entry;
    * a `postgres` `table` or `repo` other than the `use` options.

  Other section options (`resource do base_filter ... end`,
  `multitenancy`, the rest of `postgres`) are not checked yet. They would
  compile without `mix kumi.expand` printing them, so set them in plain
  Ash only.

  ## Implementation note

  `use Ash.Resource` is emitted immediately (here, in `__using__`) — same
  position as in a hand-written resource — so this module's Spark/Ash DSL
  identity is established at the normal point in compilation. Its options
  come from `Kumi.Resource.Codegen.use_opts/1`, the same list
  `generate/3` prints on the generated `use` line. `fields do
  ... end`, once it has the field specs, generates the full resource
  source (`Kumi.Resource.Codegen.generate/3`), reparses it, and splices
  everything *except* the `use Ash.Resource` line (already applied) back
  into the module at the `fields` call site — so `postgres`/`actions`/
  `attributes`/`relationships` land exactly where they would in
  hand-written source, as ordinary sequential code, before Ash's own
  `@before_compile` finalizes the DSL.
  """

  defmacro __using__(opts) do
    Kumi.Resource.Codegen.validate_opts!(opts)
    caller = __CALLER__
    resolved_opts = Enum.map(opts, fn {k, v} -> {k, resolve_alias(v, caller)} end)
    # Stored via Module.put_attribute (not `@kumi_resource_opts unquote(...)`
    # inside the quote below) so it's synchronously visible to `fields/1`'s
    # own macro-expansion-time read later in this module — module attributes
    # assigned as *generated code* aren't guaranteed visible to a sibling
    # macro's expansion-time `Module.get_attribute/2` call until the whole
    # module finishes (only `@before_compile` is guaranteed to see them).
    Module.put_attribute(caller.module, :kumi_resource_opts, resolved_opts)

    quote do
      import Kumi.Resource, only: [fields: 1]
      @kumi_resource_fields_declared? false

      # The same options `Codegen.generate/3` prints on its `use` line.
      use Ash.Resource, unquote(Kumi.Resource.Codegen.use_opts(resolved_opts))

      # Registered AFTER `use Ash.Resource` on purpose: Elixir runs
      # `@before_compile` hooks in registration order, and `use Ash.Resource`
      # registers Spark's own hook — the one that builds
      # `@spark_dsl_config`. Ours has to run second to see it.
      # `verify_no_extra_ash!/1` asserts the config is there, so if a future
      # Spark/Ash version changes this ordering the build fails loudly
      # instead of silently skipping the D1 check.
      @before_compile Kumi.Resource
    end
  end

  @doc "Declares this resource's fields and relationships. See the moduledoc."
  defmacro fields(do: block) do
    caller_module = __CALLER__.module
    opts = Module.get_attribute(caller_module, :kumi_resource_opts)
    specs = Kumi.Resource.FieldSpec.parse(block, __CALLER__)
    source = Kumi.Resource.Codegen.generate(caller_module, opts, specs)
    members = Kumi.Resource.Codegen.emitted_members(specs)

    {:defmodule, _meta, [_alias, [do: body]]} = Code.string_to_quoted!(source)
    # First form is always `use Ash.Resource, ...` — already applied by
    # `__using__`, from the same `Codegen.use_opts/1`. Assert that shape so a
    # Codegen refactor can't silently drop a real section here instead. Only
    # the shape: the reparsed options hold alias AST where `__using__` passed
    # module atoms, so comparing the two would never match.
    {:__block__, block_meta, [{:use, _, _} | rest]} = body
    sections = {:__block__, block_meta, rest}

    quote do
      @kumi_resource_fields_declared? true
      unquote(sections)

      @kumi_expand_source unquote(source)
      @doc false
      @spec __kumi_expand__() :: String.t()
      def __kumi_expand__, do: @kumi_expand_source

      # The member names `fields do ... end` generated, compared against the
      # DSL Ash actually accepted — see `__before_compile__/1`.
      @kumi_expand_members unquote(Macro.escape(members))
    end
  end

  defmacro __before_compile__(env) do
    unless Module.get_attribute(env.module, :kumi_resource_fields_declared?, false) do
      raise CompileError,
        description:
          "Kumi.Resource: #{inspect(env.module)} is missing a `fields do ... end` block",
        file: env.file,
        line: env.line
    end

    verify_no_extra_ash!(env)

    :ok
  end

  # Sections `fields do ... end` never writes anything into, so any entry
  # at all is extra. Listed one by one rather than found by sweeping every
  # path in the config: Ash's transformers have already run by the time
  # `verify_no_extra_ash!/1` does, and add entities of their own (the four
  # default actions, a `belongs_to`'s `*_id` attribute), so what counts as
  # generated has to be decided per section.
  @never_generated [
    [:code_interface],
    [:validations],
    [:changes],
    [:preparations],
    [:postgres, :custom_indexes],
    [:postgres, :check_constraints],
    [:postgres, :custom_statements]
  ]

  # H1 (blueprint §0 D1): a plain `attributes do ... end` (or
  # `relationships`/`calculations`/`aggregates`/`identities`/`validations`/
  # `postgres do references do ... end end`, ...) block dropped in alongside
  # `fields do ... end` compiles fine — Ash has no idea the two came from
  # different places — but `mix kumi.expand` prints only what `fields`
  # generated, silently breaking "expand always prints exactly what
  # compiles".
  #
  # The comparison reads Spark's accumulated `@spark_dsl_config` rather than
  # `Ash.Resource.Info.*`. Two reasons, both empirically checked:
  #
  #   1. It works here. `use Ash.Resource` expands at the top of
  #      `__using__/1`, so Spark's own `@before_compile` is registered first
  #      and has already populated the config by the time this one runs —
  #      every section's entities are visible, including a `belongs_to`'s
  #      implicit `*_id` attribute.
  #   2. It sees `public? false` members. `Ash.Resource.Info` has no
  #      `relationships/1` counterpart to `public_relationships/1` that is
  #      safe to call this early, and a private relationship bolted on
  #      alongside the shorthand is exactly as invisible to `kumi.expand` as
  #      a public one.
  #
  # Doing it here rather than from `@after_verify` also keeps the failure
  # readable: `@after_verify` runs inside `Module.ParallelChecker`, so its
  # raise reaches the user wrapped in an `** (EXIT from #PID<...>)` dump.
  # A `CompileError` from `@before_compile` points at the user's own file.
  #
  # `policies` is not checked: `policies do ... end` needs the
  # `Ash.Policy.Authorizer` extension, which `use Kumi.Resource` never adds
  # (and refuses to be given, see `Codegen.validate_opts!/1`), so it
  # already fails on its own with `undefined function policies/1`.
  #
  # Section *options* are only checked for `postgres`'s `table` and `repo`,
  # the two `generate/3` writes. Others (`resource do base_filter ... end`,
  # `multitenancy`, the remaining `postgres` options) are not checked yet.
  defp verify_no_extra_ash!(env) do
    expected = Module.get_attribute(env.module, :kumi_expand_members)
    config = Module.get_attribute(env.module, :spark_dsl_config)

    # Never treat an unavailable config as "nothing extra found" — that
    # turns this check into a silent no-op, which is exactly the class of
    # bug it exists to prevent.
    if is_nil(config) do
      raise CompileError,
        description:
          "Kumi.Resource: cannot read Spark's DSL config for #{inspect(env.module)}, so the " <>
            "`mix kumi.expand` completeness check (blueprint §0 D1) could not run. This means " <>
            "Spark's @before_compile ordering changed — the check must be repaired, not skipped.",
        file: env.file,
        line: env.line
    end

    named_extras =
      [
        {[:attributes], & &1.name, expected.attributes},
        {[:relationships], & &1.name, expected.relationships},
        {[:actions], & &1.name, expected.actions},
        {[:calculations], & &1.name, []},
        {[:aggregates], & &1.name, []},
        {[:identities], & &1.name, expected.identities},
        {[:postgres, :references], & &1.relationship, expected.references}
      ]
      |> Enum.map(fn {path, name_of, expected_names} ->
        {path, Enum.map(entities(config, path), name_of) -- expected_names}
      end)
      |> Enum.reject(fn {_path, names} -> names == [] end)
      |> Enum.map(fn {path, names} -> {path, inspect(names)} end)

    unexpected_entries =
      @never_generated
      |> Enum.map(&{&1, length(entities(config, &1))})
      |> Enum.reject(fn {_path, count} -> count == 0 end)
      |> Enum.map(fn {path, count} -> {path, "#{count} declared"} end)

    extras = named_extras ++ unexpected_entries ++ overridden_postgres_opts(env.module, config)

    if extras != [] do
      raise CompileError,
        description: extra_ash_message(env.module, extras),
        file: env.file,
        line: env.line
    end

    :ok
  end

  defp entities(config, path), do: get_in(config, [path, :entities]) || []

  # `generate/3` also writes `table` and `repo` into `postgres do ... end`,
  # from the `use Kumi.Resource` options. A second `postgres do table ...
  # end` replaces the value rather than failing, so compare the result.
  defp overridden_postgres_opts(module, config) do
    kumi_opts = Module.get_attribute(module, :kumi_resource_opts)
    postgres_opts = get_in(config, [[:postgres], :opts]) || []

    [:table, :repo]
    |> Enum.map(&{&1, Keyword.get(postgres_opts, &1), Keyword.fetch!(kumi_opts, &1)})
    |> Enum.reject(fn {_key, compiled, declared} -> compiled == declared end)
    |> Enum.map(fn {key, compiled, declared} ->
      {[:postgres, key], "#{inspect(compiled)} (`use Kumi.Resource` says #{inspect(declared)})"}
    end)
  end

  defp extra_ash_message(module, extras) do
    lines = Enum.map(extras, fn {path, found} -> "  #{Enum.join(path, ".")}: #{found}" end)

    """
    Kumi.Resource: #{inspect(module)} declares plain Ash DSL sections that \
    `fields do ... end` did not generate:

    #{Enum.join(lines, "\n")}

    `mix kumi.expand` only prints what `fields do ... end` generates, so it \
    would not print these — the shorthand cannot be used for this module \
    (blueprint §0 D1 "Show Ash": `mix kumi.expand` must always print \
    exactly what compiles).

    Escape hatch: run `mix kumi.expand #{inspect(module)}`, paste its \
    output into this module in place of `fields do ... end`, and continue \
    in plain Ash — add the extra attributes/relationships/etc. there.
    """
  end

  defp resolve_alias({:__aliases__, _, _} = ast, env), do: Macro.expand(ast, env)
  defp resolve_alias(other, _env), do: other
end
